###
#  Runtime configuration
##
server:
  name: cluster1
  linkpass: linkP@ss
  vhost: nexus1.omega-services.org

listeners:
  primary:
    host: localhost
    port: 8000

database:
  adapter: sqlite3
  database: omega_development
  username: root
  password: morgan
  hostname: localhost
