


CONFIG_PATH = "#{PATH}/config/"
SRC_DIR     = "#{PATH}/src/"
MODEL_DIR   = "#{PATH}/src/models/"
LOG_PATH	= "#{PATH}/logs/"


STATE_SHUTDOWN = -1
STATE_STARTUP  =  0
STATE_RUNNING  =  1


VERSION_RELEASE = "Backdraft"
VERSION_MAJOR = 0
VERSION_MINOR = 1
VERSION_PATCH = 0

VERSION_STRING = "#{VERSION_MAJOR}.#{VERSION_MINOR}.#{VERSION_PATCH}"  
VERSION_STRING_DOTTED = "(#{VERSION_RELEASE})-#{VERSION_MAJOR}.#{VERSION_MINOR}.#{VERSION_PATCH}"
